# Checkov Configuration for Terraform S3 Module
# This file defines security scanning rules and intentional skips

# Framework settings
framework:
- terraform

# Skip checks for intentional design choices
skip-check:
# Public access controls - These are intentionally flexible when publicly_accessible = true
- CKV_AWS_53 # S3 bucket has block public ACLs enabled (disabled when publicly_accessible = true)
- CKV_AWS_54 # S3 bucket has block public policy enabled (disabled when publicly_accessible = true)
- CKV_AWS_55 # S3 bucket has ignore public ACLs enabled (disabled when publicly_accessible = true)
- CKV_AWS_56 # S3 bucket has restrict public buckets enabled (disabled when publicly_accessible = true)

# IAM policy for public access - Only applies to publicly accessible buckets
- CKV_AWS_283 # IAM policies allow ALL AWS principal permissions (intentional for public buckets)

# Optional features that users can enable when needed
- CKV_AWS_18 # S3 bucket access logging (optional feature, can be configured)
- CKV_AWS_144 # S3 cross-region replication (optional feature, supported when configured)
- CKV2_AWS_62 # S3 event notifications (optional feature, can be configured)
- CKV2_AWS_6 # Public Access Block (handled by our logic)

# Versioning and encryption - handled by our configuration logic
- CKV_AWS_21 # S3 versioning (enabled when versioning config is provided)
- CKV_AWS_145 # S3 KMS encryption (handled by server_side_encryption_rule)
- CKV_AWS_19 # S3 encryption at rest (handled by server_side_encryption_rule)

# Module source versioning preference
- CKV_TF_1 # Module sources use commit hash (we prefer semantic versioning with tags)

# Directories to scan
directory:
- .

# Output settings
output:
- cli
- json

# Quiet mode for cleaner output
quiet: true

# Compact output format
compact: true

# Download external modules for comprehensive scanning
download-external-modules: true

# Security baseline - these checks should NEVER be skipped
# (No skips needed - all critical security checks are passing)

# Custom checks can be added here if needed
# check:
#   - CKV_AWS_300  # This should now pass with our lifecycle fix
