formatter: "markdown table"

version: ">= 0.16"

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  ## Usage

  Basic usage of this module is as follows:

  ```hcl
  module "s3_buckets" {
    source = "jcalles/s3/aws"
    version = "~> 1.0"
    
    # Required variables
    namespace      = "yourcompany"
    stage         = "dev"
    aws_region    = "us-west-2"
    aws_account_id = "YOUR_ACCOUNT_ID"
    
    # S3 buckets configuration
    buckets = {
      "data" = {
        versioning_enabled = true
        encryption_enabled = true
      }
      "logs" = {
        versioning_enabled = false
        lifecycle_rules_enabled = true
      }
    }
    
    tags = {
      Environment = "development"
      Project     = "example"
    }
  }
  ```

  ## Examples

  - [Basic Usage](./examples/basic/) - Simple S3 bucket creation
  - [Advanced Usage](./examples/advanced/) - Multiple buckets with custom configurations

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
